baseurl = "/"
title = "swengineer"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Toby Stayner"
    description = "Toby Stayner's personal website"
    keywords = "blog,developer,personal"
    info = "Software Engineer BE(Hons)"
    avatarurl = "images/avatar.jpg"
    # footercontent = "Enter a text here."

    dateformat = "2 January 2006"

    hideFooter = true
    hideCredits = false
    hideCopyright = false
    since = 2019

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "GitHub"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/tobyjzstay/"
[[params.social]]
    name = "GitLab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.ecs.vuw.ac.nz/staynetoby/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/toby-stayner/"
[[params.social]]
    name = "Email"
    icon = "fa fa-at"
    weight = 4
    url = "mailto:toby@swengineer.dev"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "PROJECTS"
            weight = 1
            url = "projects/"
