version: "3"

services:
  client:
    build: client/
    ports:
      - "3000:3000"
    volumes:
      - ./client/build:/client/build
  server:
    build: server/
    depends_on:
      - client
    ports:
      - "8080:8080"
    volumes_from:
      - client

