name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Add pnpm to PATH
              run: |
                  echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
            - name: Create .env file
              run: |
                  echo "API_SECRET=${{ secrets.API_SECRET }}" >> .env
                  echo "CRYPTO_SIZE=${{ vars.CRYPTO_SIZE }}" >> .env
                  echo "GMAIL_EMAIL=${{ secrets.GMAIL_EMAIL }}" >> .env
                  echo "GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}" >> .env
                  echo "GMAIL_SENDER=${{ secrets.GMAIL_SENDER }}" >> .env
                  echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
                  echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
                  echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
                  echo "NODE_ENV=${{ vars.NODE_ENV }}" >> .env
                  echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
                  echo "HOSTNAME=${{ vars.HOSTNAME }}" >> .env
                  echo "PORT=${{ vars.PORT }}" >> .env
                  echo "SALT_ROUNDS=${{ vars.SALT_ROUNDS }}" >> .env
            - name: Install dependencies
              run: |
                  pnpm --prefix ./client/ install --frozen-lockfile
            - name: Build the project
              run: |
                  pnpm --prefix ./client/ build
            - name: Copy client build to host
              run: |
                  cp -r client/build/* /var/www/swengineer/
